### ISSUE TITLE
Signing and verifying signatures 

### ISSUE THREAD

**Issue by EduardoRFS** [marigold-dev/tztools#1]
A page where I could put an edsk + hash to generate an edsig. Also another where I can put edpk + edsig + hash and it says if it checks or not.

**Comment by fraidev** [comment]
Resolved with https://github.com/marigold-dev/tztools/commit/ecf0d2d535516a73089de6f6267eb65b0a59fe74 and https://github.com/marigold-dev/tztools/commit/3d179e42811aca569bfd2b8624e3358df91bd80b
